print("hello"+"world")
print("my"+"pleasure")
print("bye"+"hi")
print("teach"+"tutorial")
print("hi"+"teach")
print("hello"+"world")
print("my"+"pleasure")
print("bye"+"hi")
print("teach"+"tutorial")
print("hi"+"teach")
print("hello"+"world")
print("my"+"pleasure")
print("bye"+"hi")
print("teach"+"tutorial")
print("hi"+"teach")
print("hello"+"world")
print("my"+"pleasure")
print("bye"+"hi")
print("teach"+"tutorial")
print("hi"+"teach")

age = input("please enter your age ")
print(age)